VALORES_INVALIDOS_BAIRRO = {
    "bairro ficticio",
    "bairro nao informado",
    "bairro nao localizad",
    "indicacoes cancelada",
    "nao encontrado",
    "nao informado",
    "nf",
    "ni",
    "sem dados",
}

REGIAO_METROPOLITANA = {
    "bairro oliveira",
    "barro preto",
    "belas aguas",
    "borda do campo",
    "braga",
    "campinha grande do s",
    "campo de sao benedit",
    "campo pequeno",
    "canguiri",
    "colombo",
    "colonia faria",
    "colonia sao venancio",
    "estados",
    "estancia pinhais",
    "eucaliptos",
    "formoso",
    "gralha azul",
    "guatupe",
    "iguacu 01",
    "iguacu 1",
    "ipe 2",
    "jardim boa vista",
    "jardim bom pastor",
    "jardim loanda",
    "jardim osasco",
    "jardim pedro demete",
    "jardim rafaela",
    "jardim santa monica",
    "jardim weissopolis",
    "jd dona belizaria",
    "jd europa",
    "jd orestes tha",
    "jd suissa",
    "jr taisa",
    "lot marinoni",
    "loteamento sao geron",
    "maria antonieta",
    "maua",
    "menino deus",
    "nacoes",
    "osasco",
    "ouro fino",
    "palmeirinha",
    "parque da fonte",
    "parque das fontes",
    "parque das nascentes",
    "pineville",
    "pinhais",
    "piraquara",
    "planta deodoro",
    "planta meireles",
    "quatro barras",
    "rainha",
    "rio verde",
    "roca grande",
    "roca negra",
    "santa monica",
    "santa teresinha",
    "santa terezinha",
    "santo antonio",
    "sao benedito",
    "sao geronimo",
    "sao jose",
    "sao jose dos pinhais",
    "tamandare",
    "thomas coelho",
    "thomaz coelho",
    "veneza",
    "vila graziela",
    "vila ipanema",
    "vila maria antonieta",
    "casa",
}

MAPA_BAIRRO = {
    "ahao": "ahu",
    "alto da gla3ria": "alto da gloria",
    "barigua": "barigui",
    "capanema": "jardim botanico",
    "centro cavico": "centro civico",
    "cic": "cidade industrial",
    "cidade industrial de": "cidade industrial",
    "francisco gorski": "cidade industrial",
    "guaara": "guaira",
    "higiena3polis": "higienopolis",
    "jardim das amaricas": "jardim das americas",
    "jardim industrial": "cidade industrial",
    "juvevaa": "juveve",
    "linda3ia": "lindoia",
    "monte rey": "boqueirao",
    "mercaas": "merces",
    "mossunguaa": "mossungue",
    "passaaona": "passauna",
    "pca espanha": "bigorrilho",
    "rebouaas": "reboucas",
    "santa quitaria": "santa quiteria",
    "satio cercado": "sitio cercado",
    "sit cercado": "sitio cercado",
    "sao lourenao": "sao lourenco",
    "sao cristovao": "santa felicidade",
    "sao braz": "santa felicidade",
    "sao joao": "santa felicidade",
    "sao jorge": "portao",
    "sao judas tadeu": "capao raso",
    "sao pedro": "xaxim",
    "sao sebastiao": "ahu",
    "sao thomas": "seminario",
    "sao thomaz": "seminario",
    "sitio das palmeiras": "bacacheri",
    "tindiquera": "bairro alto",
    "vila bancaria": "campo largo",
    "vila formosa": "portao",
}
