DEFAULT_DROP_COLUMNS = (
    "OCORRENCIA_CODIGO",
    "REGIONAL_FATO_NOME",
    "SECRETARIA_NOME",
    "SITUACAO_EQUIPE_DESCRICAO",
    "OCORRENCIA_DATA",
    "OPERACAO_DESCRICAO",
    "ORIGEM_CHAMADO_DESCRICAO",
)

COLUNAS_TEXTO = (
    "ATENDIMENTO_BAIRRO_NOME",
    "EQUIPAMENTO_URBANO_NOME",
    "LOGRADOURO_NOME",
    "NATUREZA1_DESCRICAO",
    "NATUREZA2_DESCRICAO",
    "NATUREZA3_DESCRICAO",
    "NATUREZA4_DESCRICAO",
    "NATUREZA5_DESCRICAO",
    "SUBCATEGORIA1_DESCRICAO",
    "SUBCATEGORIA2_DESCRICAO",
    "SUBCATEGORIA3_DESCRICAO",
    "SUBCATEGORIA4_DESCRICAO",
    "SUBCATEGORIA5_DESCRICAO",
    "SECRETARIA_SIGLA",
    "SERVICO_NOME",
    "NUMERO_PROTOCOLO_156",
)

COLUNAS_BINARIAS = (
    "FLAG_EQUIPAMENTO_URBANO", 
    "FLAG_FLAGRANTE",
    "NATUREZA1_DEFESA_CIVIL",
    "NATUREZA2_DEFESA_CIVIL",
    "NATUREZA3_DEFESA_CIVIL",
    "NATUREZA4_DEFESA_CIVIL",
    "NATUREZA5_DEFESA_CIVIL",

)

COLUNAS_INT = "OCORRENCIA_DIA_SEMANA"

MAPA_DIA_SEMANA = {
    "domingo": 1,
    "segunda": 2,
    "segunda-feira": 2,
    "terca": 3,
    "terca-feira": 3,
    "quarta": 4,
    "quarta-feira": 4,
    "quinta": 5,
    "quinta-feira": 5,
    "sexta": 6,
    "sexta-feira": 6,
    "sabado": 7,
}

COLUNA_HORA = "OCORRENCIA_HORA"
